AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: S3EventInvokeStepFunction
      Description: 'Event rule to trigger Step Functions from S3 events'
      State: ENABLED
      RoleArn: 'arn:aws:iam::266747933355:role/LabRole'
      EventPattern:
        source:
          - 'aws.s3'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventSource:
            - 's3.amazonaws.com'
            - 's3.amazonaws.com.cn'
          eventName:
            - 'PutObject'
            - 'CompleteMultipartUpload'
      Targets:
        - Arn: 'arn:aws:states:us-east-1:266747933355:stateMachine:MyStateMachine'
          Id: "TargetStepFunctionMachineFunction"
          RoleArn: 'arn:aws:iam::266747933355:role/LabRole'
